version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: quarkus_db
      MARIADB_USER: root
      MARIADB_PASSWORD: secret
    volumes:
      - mariadb_data:/var/lib/mysql

  infinispan:
    image: quay.io/infinispan/server:15.1
    container_name: infinispan
    restart: always
    ports:
      - "11222:11222"
    environment:
      USER: admin
      PASS: password
      JAVA_OPTS: "-Xms512m -Xmx512m"
    command:
      - /opt/infinispan/bin/server.sh
      - -c
      - infinispan.xml

volumes:
  mariadb_data:
